### ISSUE TITLE
Data tables counts - duplicate and missing table

### ISSUE THREAD

**Issue by MaximMoinat** [EHDEN/CdmInspection#21]
In the clinical data table counts:
* drug exposure listed twice (line 11 and line 23)
* visit occurrence is missing
* Inconsistent naming (sometimes table name with underscore, sometimes without)

Also, a consisted sorting would be nice. Either on table name or on count (descending).

https://github.com/EHDEN/CdmInspection/blob/daeadb7a2ad7423691f8c9a92259c47f40f6556b/inst/sql/sql_server/checks/data_tables_count.sql#L1-L40

**Comment by PRijnbeek** [comment]
Great thanks
