### ISSUE TITLE
baseUrl - default "http://atlas-demo.ohdsi.org/WebAPI"

### ISSUE THREAD

**Issue by scossin** [EHDEN/CdmInspection#40]
We ran the program ("CodeToRun.R") and we encountered no error.   
However we realized afterwards that we didn't change the baseUrl that has default "http://atlas-demo.ohdsi.org/WebAPI". We changed the baseUrl and it worked but the baseUrl is not in the report, so it's not clear if we used the default value or our WebAPI installation.  
 
If it's a security issue to add the baseUrl in the report, one solution might be to add a boolean in the report: whether or not the default "http://atlas-demo.ohdsi.org/WebAPI" was used or not.

**Comment by PRijnbeek** [comment]
I think it is then not clear enough you have to change this to your own link. We cannot know your location of atlas. The atlas-demo is just an example. it would we better is we do not provide the example so you would see it could not find it if you had not changed. Will fix this in dev now and we will merge this in the new version later
