### ISSUE TITLE
"This document contains fields that may refer to other files"

### ISSUE THREAD

**Issue by MaximMoinat** [EHDEN/CdmInspection#61]
When I open an inspection report, I always get the question to update fields that 'refer to other files'. Sometimes I click yes, sometimes no, and see no difference.

What triggers this message? And does it actually make a difference whether you let Word update these fields or not?

![image](https://user-images.githubusercontent.com/17825660/117012863-a0363380-acef-11eb-9134-f17491d55484.png)

**Comment by PRijnbeek** [comment]
You have to click yes to get the table of content

**Comment by MaximMoinat** [comment]
Ah, thanks! Somehow I never noticed that.
