### ISSUE TITLE
vocabDatabaseSchema parameter is not passed to performanceChecks

### ISSUE THREAD

**Issue by KalleMedisapiens** [EHDEN/CdmInspection#81]
https://github.com/EHDEN/CdmInspection/blob/master/R/CdmInspection.R#L182
https://github.com/EHDEN/CdmInspection/blob/master/R/PerformanceChecks.R#L47
https://github.com/EHDEN/CdmInspection/blob/master/inst/sql/sql_server/checks/performance_benchmark.sql#L5

vocabDatabaseSchema parameter is not passed to the performanceChecks function and it defaults to cdmDatabaseSchema. That makes performance_benchmark.sql look for concept table in cdm schema instead of vocabulary schema. 
Just adding vocabDatabaseSchema = vocabDatabaseSchema should fix it.

**Comment by MaximMoinat** [comment]
Thanks for reporting, we will incorporate this in the upcoming 1.1 release #78
