### ISSUE TITLE
Error when generating the results document

### ISSUE THREAD

**Issue by sutsabs** [EHDEN/CdmInspection#96]
generateResultsDocument(
results,
outputFolder,
docTemplate = "EHDEN",
authors=authors,
databaseId = databaseId,
databaseName = databaseName,
databaseDescription = databaseDescription,
smallCellCount = smallCellCount,
silent = FALSE
)

```
Error in order(df_t1$COUNT, decreasing = TRUE) : 
  argument 1 is not a vector
```

I was able to run the cmdInspection() and generate the results. I ran this for marketscan and verified that the results were generated correctly. Now I am trying to generate the report and immidiately I encounter this error.

[log_cdmInspection.txt](https://github.com/EHDEN/CdmInspection/files/12794572/log_cdmInspection.txt)

**Comment by katiasantaca** [comment]
did u solve the issue? I have the same problem
